№1 (2 балла)  
Используя средства библиотеки Numpy, без циклов, выполните следующие задания:  
- a) Создайте массив arr_1 размером 3х4, все элементы которого равны 3. 
- b) Создайте массив arr_2, заполненный случайными целыми числами от 0 до 9, размером 2х4. 
- c) Выведите на экран количество элементов в созданных массивах arr_1 и arr_2. 
- d) Соедините массивы arr_1 и arr_2 по нулевой оси. 
- e) Создайте массив arr_3 из кортежа чисел (1, 8, 6, 5, 8, 3) с помощью функции np.array(). 
- f) Умножьте каждый элемент массива arr_3 на число 3 и прибавьте к каждому элементу 1. 
Результат запишите в новый массив arr_4. 
- g) Преобразуйте массив arr_3 к двумерному массиву 2х3. Результат запишите в массив arr_5. 
- h) Определите минимальные элементы массива arr_5 вдоль первой оси. 
- i) Вычислите среднее арифметическое всех элементов массива arr_5. 
- j) Создайте массив arr_6, состоящий из квадратов чисел от 0 до 10.
- k) Выведите каждый второй элемент массива arr_6. 
- l) Выведите элементы массива arr_6 в обратном порядке. 
- m) Каждому второму элементу массива arr_6 присвойте значение 2. 
- n) Проверьте, есть ли в массиве arr_6 значение 49. 
- o) Создайте двумерный массив А, состоящий из положительных и отрицательных чисел. Из 
массива A выберите все отрицательные элементы и запишите их в одномерный массив B.

In [ ]:
import numpy as np

# a) Массив 3x4, все элементы равны 3
arr_1 = np.full((3, 4), 3)

# b) Массив 2x4, случайные целые от 0 до 9
arr_2 = np.random.randint(0, 10, (2, 4))

# c) Количество элементов в массивах
print("размер arr_1:", arr_1.size)
print("размер arr_2:", arr_2.size)

# d) Соединение по нулевой оси
arr_concat = np.concatenate([arr_1, arr_2], axis=0)
print("Concatenated array:\n", arr_concat)

# e) Массив из кортежа
arr_3 = np.array((1, 8, 6, 5, 8, 3))

# f) Умножение и прибавление
arr_4 = arr_3 * 3 + 1
print("arr_4:", arr_4)

# g) Преобразование в 2x3
arr_5 = arr_3.reshape(2, 3)
print("arr_5:\n", arr_5)

# h) Минимальные элементы вдоль первой оси
min_elements = arr_5.min(axis=0)
print("Минимальные элементы вдоль первой оси:", min_elements)

# i) Среднее арифметическое всех элементов arr_5
mean_arr_5 = arr_5.mean()
print("Среднее arr_5:", mean_arr_5)

# j) Массив квадратов от 0 до 10
arr_6 = np.arange(11) ** 2
print("arr_6:", arr_6)

# k) Каждый второй элемент arr_6
print("Каждый второй элемент arr_6:", arr_6[::2])

# l) arr_6 в обратном порядке
print("arr_6 в обратном порядке:", arr_6[::-1])

# m) Каждому второму элементу присвоить 2
arr_6[1::2] = 2
print("arr_6 после изменения:", arr_6)

# n) Проверка наличия 49
print("Есть ли 49 в arr_6:", 49 in arr_6)

# o) Двумерный массив A и выбор отрицательных элементов
A = np.array([[1, -2, 3], [-4, 5, -6]])
B = A[A < 0]
print("Отрицательные элементы массива A:", B)

arr_1 size: 12
arr_2 size: 8
Concatenated array:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [0 3 3 2]
 [6 8 4 5]]
arr_4: [ 4 25 19 16 25 10]
arr_5:
 [[1 8 6]
 [5 8 3]]
Минимальные элементы вдоль первой оси: [1 8 3]
Среднее arr_5: 5.166666666666667
arr_6: [  0   1   4   9  16  25  36  49  64  81 100]
Каждый второй элемент arr_6: [  0   4  16  36  64 100]
arr_6 в обратном порядке: [100  81  64  49  36  25  16   9   4   1   0]
arr_6 после изменения: [  0   2   4   2  16   2  36   2  64   2 100]
Есть ли 49 в arr_6: False
Отрицательные элементы массива A: [-2 -4 -6]


№2 (1 балл)  
Представьте, что вы пишете компьютерную игру «Шахматы».  
Вам надо смоделировать шахматную доску, которая представляет собой numpy-матрицу. Чёрная 
клетка представляется нулём, а белая — единицей. Если смотреть на доску сверху, то левая верхняя 
клетка — белая.  
Вы уже практически реализовали задачу, ведь вы знаете, что у шахматной доски 8 столбцов и 8 
строк, но заказчик вдруг изменил требования и заявил, что в его игре доска может быть 
произвольного размера, но всегда квадратной, например, 50х50.  
Напишите функцию make_field(size), в которую поступает размер доски, и которая возвращает 
требуемый массив numpy. Тип элементов массива должен быть np.int8.  
Для решения задачи нельзя использовать циклы.

In [2]:
def make_field(size):
    return ((np.indices((size, size)).sum(axis=0) % 2).astype(np.int8))

print("Поле 5x5:\n", make_field(5))
print("Поле 10x10:\n", make_field(10))

Поле 5x5:
 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
Поле 10x10:
 [[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


№3 (1 балл)  
Напишите функцию super_sort(rows, cols), в которую поступают размеры матрицы. Вам 
необходимо:  
  
- заполнить матрицу А случайными целыми числами из диапазона [1..100] 
- сделать копию этой матрицы в матрицу B 
- упорядочить чётные столбцы матрицы B по возрастанию, а нечётные — по убыванию  
  
Верните кортеж, состоящий из матриц А и B.  
  
Для решения задачи нельзя использовать циклы. Для сортировки используйте функцию np.sort.  

In [ ]:
def super_sort(rows, cols):
    A = np.random.randint(1, 101, (rows, cols))
    B = A.copy()

    even_cols = np.arange(0, cols, 2)
    B[:, even_cols] = np.sort(B[:, even_cols], axis=0)

    odd_cols = np.arange(1, cols, 2)
    B[:, odd_cols] = np.sort(B[:, odd_cols], axis=0)[::-1]
    return A, B

A, B = super_sort(4, 5)
print("A:\n", A)
print("B:\n", B)

A:
 [[ 3 87 48  5 57]
 [11 64 22  7 54]
 [13 68  2 89 65]
 [95 94 47 60 78]]
B:
 [[ 3 94  2 89 54]
 [11 87 22 60 57]
 [13 68 47  7 65]
 [95 64 48  5 78]]


№4 (1 балл)   
Создайте массив чисел от −2𝜋 до 2𝜋. Посчитайте сумму поэлементных квадратов синуса и косинуса 
для данного массива. С помощью np.all проверьте, что в ответе только единицы.

In [6]:
arr = np.linspace(-2 * np.pi, 2 * np.pi, 100)
result = np.sin(arr) ** 2 + np.cos(arr) ** 2
print("Сумма квадратов синуса и косинуса:", result)
print("Все элементы равны 1:", np.all(np.isclose(result, 1)))

Сумма квадратов синуса и косинуса: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
Все элементы равны 1: True


№5 (2 балла)  
Создайте две numpy матрицы размера nхn и заполните их случайными значениями. Посчитайте их 
поэлементное и матричное произведения. Для этого реализуйте функции:  
1. mult – матричное перемножение без использования numpy 
2. el_mult – поэлементное перемножение без использования numpy 
3. np_mult – матричное перемножение c использованием numpy 
4. np_el_mult – поэлементное перемножение с использованием numpy  
  
При помощи timeit засеките время работы функций для n = 100000 (для чистоты эксперимента 
засекайте время на одинаковых матрицах). Во сколько раз numpy версия функций работает быстрее 
реализаций без numpy?

In [11]:
import timeit

def mult(A, B):
    n = len(A)
    result = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            s = 0
            for k in range(n):
                s += A[i][k] * B[k][j]
            result[i][j] = s
    return result

def el_mult(A, B):
    n = len(A)
    result = [[A[i][j] * B[i][j] for j in range(n)] for i in range(n)]
    return result

def np_mult(A, B):
    return np.dot(A, B)

def np_el_mult(A, B):
    return A * B

n = 400

A_np = np.random.randint(0, 10, (n, n))
B_np = np.random.randint(0, 10, (n, n))
A_list = A_np.tolist()
B_list = B_np.tolist()

t1 = timeit.timeit(lambda: mult(A_list, B_list), number=1)
t2 = timeit.timeit(lambda: el_mult(A_list, B_list), number=1)
t3 = timeit.timeit(lambda: np_mult(A_np, B_np), number=1)
t4 = timeit.timeit(lambda: np_el_mult(A_np, B_np), number=1)

print(f"mult (без numpy): {t1:.4f} сек")
print(f"el_mult (без numpy): {t2:.4f} сек")
print(f"np_mult (numpy): {t3:.4f} сек")
print(f"np_el_mult (numpy): {t4:.4f} сек")

print("Матричное умножение numpy быстрее в", round(t1/t3, 2), "раз(а)")
print("Поэлементное умножение numpy быстрее в", round(t2/t4, 2), "раз(а)")

mult (без numpy): 3.5785 сек
el_mult (без numpy): 0.0076 сек
np_mult (numpy): 0.0344 сек
np_el_mult (numpy): 0.0001 сек
Матричное умножение numpy быстрее в 104.13 раз(а)
Поэлементное умножение numpy быстрее в 52.75 раз(а)


№6 (1 балл)  
  
В статистике и задачах машинного обучения часто приходится иметь дело с функцией, которая 
вычисляется по формуле ∑(𝑦𝑖 − 𝑎𝑖)2, i меняется от 1 до n, 𝑦𝑖 — координаты одномерного 
вектора 𝑦, 𝑎𝑖 — координаты одномерного вектора 𝑎. Посчитайте для 𝑦 = (1, 2, 3, 4, 5), 𝑎 = (3, 2, 1, 0, 
−1). 

In [12]:
y = np.array([1, 2, 3, 4, 5])
a = np.array([3, 2, 1, 0, -1])
result = np.sum((y - a) ** 2)
print("Сумма квадратов разностей:", result)

Сумма квадратов разностей: 60


№7 (1 балл)  
  
Подумайте, массив какого размера получится, если перемножить массив 4×1×3 и массив 12×1. 
Убедитесь на практике в правильности вашего ответа. 

In [14]:
arr1 = np.random.randint(0, 10, (4, 1, 3))
arr2 = np.random.randint(0, 10, (12, 1))

print("arr1 shape:", arr1.shape)
print("arr2 shape:", arr2.shape)

try:
    result = arr1 * arr2
    print("Результат поэлементного умножения shape:", result.shape)
except ValueError as e:
    print("Ошибка поэлементного умножения:", e)

try:
    dot_result = np.dot(arr1, arr2)
    print("Результат np.dot shape:", dot_result.shape)
except ValueError as e:
    print("Ошибка np.dot:", e)

arr1 shape: (4, 1, 3)
arr2 shape: (12, 1)
Результат поэлементного умножения shape: (4, 12, 3)
Ошибка np.dot: shapes (4,1,3) and (12,1) not aligned: 3 (dim 2) != 12 (dim 0)


№8 (1 балл)  
  
Создайте и заполните случайными значениями матрицы A, B, C и D (размерности смотрите в 
формуле). Вычислите следующее выражение:

In [22]:
n, m = 5, 5

A = np.random.randint(1, 10, (n, m))
B = np.random.randint(1, 10, (m,))
C = np.random.randint(1, 10, (m, n))
D = np.random.randint(1, 10, (m,))

result = 5 * (A @ B) + (C.T @ D)
print("A:\n", A)
print("B:\n", B)
print("C:\n", C)
print("D:\n", D)
print("Результат:\n", result)

A:
 [[9 8 2 2 3]
 [9 3 8 4 8]
 [6 2 9 9 4]
 [2 1 9 2 6]
 [3 4 9 4 1]]
B:
 [8 8 3 4 8]
C:
 [[1 1 8 1 8]
 [6 5 6 3 8]
 [3 4 4 8 3]
 [8 1 4 1 5]
 [3 3 3 5 5]]
D:
 [3 3 1 3 9]
Результат:
 [ 945 1052  880  603  646]


№9 (1 балл)  
В машинном обучении есть модель линейной регрессии, для которой "хорошее" решение считается 
по следующей формуле:  
Вычислите результат формулы для: 

In [28]:

X = np.array([[-3, 4, 1],
              [4, 3, 1]])

y = np.array([10, 12])

lambd = 0.1

I = np.eye(3)

theta = np.linalg.inv((X.T @ X + lambd * I) ** -1) @ X.T @ y

print("Результат (theta):", theta)

Результат (theta): [ 0.   0.  46.2]


C:\Users\gigan\AppData\Local\Temp\ipykernel_60660\2334280540.py:10: RuntimeWarning: divide by zero encountered in reciprocal
  theta = np.linalg.inv((X.T @ X + lambd * I) ** -1) @ X.T @ y


№10 (2 балла)  
Напишите программу, которая будет решать систему линейных уравнений вида:  
Коэффициенты и правую часть вводит пользователь. Программа выводит решение системы. Для 
нахождения решения используйте numpy.linalg.solve.   
Система не имеет решения (или имеет их бесконечно много), если определитель матрицы 
коэффициентов равен 0. В этом случае необходимо выводить соответствующее сообщение. Для 
нахождения определителя используйте функцию numpy.linalg.det.

In [29]:
a11 = float(input("Введите коэффициент a11: "))
a12 = float(input("Введите коэффициент a12: "))
a21 = float(input("Введите коэффициент a21: "))
a22 = float(input("Введите коэффициент a22: "))
b1 = float(input("Введите правую часть b1: "))
b2 = float(input("Введите правую часть b2: "))

A = np.array([[a11, a12],
              [a21, a22]])

b = np.array([b1, b2])

det = np.linalg.det(A)

if np.isclose(det, 0):
    print("Система не имеет единственного решения (определитель равен 0).")
else:
    solution = np.linalg.solve(A, b)
    print("Решение системы:", solution)

Решение системы: [ 0.2 -0.1]


№11 (2 балла)  
Используя numpy, без питоновских циклов сконвертируйте цветное изображение в чёрно-белое по 
формуле:  
  
C = 0.2989 * R + 0.5870 * G + 0.1140 * B  
  
Считается, что вычисленный таким образом цвет лучше всего подходит для человеческого глаза, 
поскольку яркость каждой компоненты глаз воспринимает по-разному.  
  
Напишите функцию bw_convert(), в которой проведите все необходимые операции.  
Не забудьте, что значение каждой составляющей цвета — целое число, поэтому результат 
необходимо округлить. Для этого воспользуйтесь методом round() из библиотеки numpy.   
Используйте формат изображения RGB и библиотеку pillow.

In [32]:
from PIL import Image
import numpy as np

def bw_convert(image_path, save_path=None):
    img = Image.open(image_path).convert('RGB')
    arr = np.array(img)
    bw = np.round(0.2989 * arr[..., 0] + 0.5870 * arr[..., 1] + 0.1140 * arr[..., 2]).astype(np.uint8)
    bw_img = Image.fromarray(bw, mode='L')
    if save_path:
        bw_img.save(save_path)
    return bw_img

bw_img = bw_convert('input.jpg', 'output_bw.jpg')
bw_img.show()

№12 (2 балла)  
В материалах к лабораторной работе лежит файл ABBREV.csv. Это – текстовый файл в кодировке 
UTF-8, в котором записана таблица данных, а данные в строчках разделены символом «точка-с
запятой».  
Файл создан департаментом сельского хозяйства США и в нём указаны продукты и содержание в 
них некоторых витаминов, минералов, а также калорийность на единицу массы.  
Для чтения данных из этого файла в объект numpy.ndarray воспользуйтесь методом genfromtxt() из 
библиотеки numpy. 
table = np.genfromtxt(’ABBREV.csv’, delimiter=’;’, dtype=None, names=True, encoding="utf8") 
Вычислите и выведите на отдельных строчках названия самого-самого продукта по различным 
критериям. 
- Cамый калорийный. Если их несколько, то выведите тот, у кого название в словаре стоит 
позже всех других. 
- Самый полезный по содержанию сахара. Если их много, то выведите тот, у кого название в 
словаре стоит на первом месте. 
- Самый протеино-накачанный. Если имеется несколько вариантов, то снова выведите 
младший в словаре по названию. 
- Самый богатый витамином С. Такой продукт точно один.  
  
Помните, что «самый-самый» – это не обязательно максимальная характеристика. 
Поиск продуктов необходимо выполнять только c использованием средств библиотеки numpy. 